resources:
  - "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret
    name: ingress_server_certificate
    tls_certificate:
      certificate_chain:
        filename: /run/platform-secrets/ingress/server.crt
      private_key:
        filename: /run/platform-secrets/ingress/server.key
